"""versions and fix version

Revision ID: c0bb8fd1c862
Revises: 6821b09e9b62
Created: 2026-10-01 19:59:38.771792
"""
from alembic import op
import sqlalchemy as sa


revision = 'c0bb8fd1c862'
down_revision = '6821b09e9b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_versions_space_id'), ['space_id'], unique=False)

    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        # Named explicitly: SQLite rebuilds the table to alter it (batch mode) and cannot
        # reference an anonymous constraint, so an unnamed key fails on SQLite and leaves the
        # downgrade un-runnable on both backends.
        batch_op.create_foreign_key('fk_work_items_version_id_versions', 'versions',
                                    ['version_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_items_version_id_versions', type_='foreignkey')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versions_space_id'))

    op.drop_table('versions')
    # ### end Alembic commands ###
