"""custom fields

Revision ID: ff0b96995398
Revises: 809a4a2fbee9
Created: 2026-10-01 21:05:23.662039
"""
from alembic import op
import sqlalchemy as sa


revision = 'ff0b96995398'
down_revision = '809a4a2fbee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_fields_space_id'), ['space_id'], unique=False)

    with op.batch_alter_table('work_items', schema=None) as batch_op:
        # A NOT NULL column cannot be added to a table that already has rows unless those rows
        # get a value, so the default fills them in. It is then dropped, because the application
        # always writes the key explicitly and a lingering server default hides mistakes.
        batch_op.add_column(sa.Column('custom', sa.JSON(), nullable=False,
                                      server_default=sa.text("'{}'")))
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.alter_column('custom', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_column('custom')

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_fields_space_id'))

    op.drop_table('custom_fields')
    # ### end Alembic commands ###
